// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exapmcouqytpibllktma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4YXBtY291cXl0cGlibGxrdG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDM3ODcsImV4cCI6MjA2MDU3OTc4N30.-nt-xt7nXsSaB3NC4ogqegSyDWzTCsI5ZDiusUMA-Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);